/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/profile/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Profile */
    get: operations['get_profile_api_v1_profile_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/profile/language': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Language */
    put: operations['update_language_api_v1_profile_language_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/sources/capabilities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Capabilities */
    get: operations['capabilities_api_v1_admin_sources_capabilities_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/sources/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Source */
    post: operations['upload_source_api_v1_admin_sources_upload_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/sources/paste': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Paste Source */
    post: operations['paste_source_api_v1_admin_sources_paste_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/sources/{source_id}/review': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Review */
    get: operations['get_review_api_v1_admin_sources__source_id__review_get'];
    /** Update Review */
    put: operations['update_review_api_v1_admin_sources__source_id__review_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/sources/{source_id}/original': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Original */
    get: operations['get_original_api_v1_admin_sources__source_id__original_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/sources/{source_id}/job': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Job */
    get: operations['get_job_api_v1_admin_sources__source_id__job_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/sources/{source_id}/retry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Retry Source */
    post: operations['retry_source_api_v1_admin_sources__source_id__retry_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/policies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Policies */
    get: operations['list_policies_api_v1_admin_policies_get'];
    put?: never;
    /** Create Policy */
    post: operations['create_policy_api_v1_admin_policies_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/policies/{policy_id}/viewer': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Policy Viewer */
    get: operations['policy_viewer_api_v1_admin_policies__policy_id__viewer_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/versions/{version_id}/access': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Access */
    put: operations['update_access_api_v1_admin_versions__version_id__access_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/sources/{source_id}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve Structure */
    post: operations['approve_structure_api_v1_admin_sources__source_id__approve_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/versions/{version_id}/prepare-publication': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Prepare Publication */
    post: operations['prepare_publication_api_v1_admin_versions__version_id__prepare_publication_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/versions/{version_id}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish Version */
    post: operations['publish_version_api_v1_admin_versions__version_id__publish_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/policies/{policy_id}/rollback/{version_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rollback Version */
    post: operations['rollback_version_api_v1_admin_policies__policy_id__rollback__version_id__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/versions/{version_id}/diff': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Version Diff */
    get: operations['version_diff_api_v1_admin_versions__version_id__diff_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/versions/{version_id}/duplicates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Duplicate Sections */
    get: operations['duplicate_sections_api_v1_admin_versions__version_id__duplicates_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/policies/{policy_id}/deactivate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Deactivate Policy */
    post: operations['deactivate_policy_api_v1_admin_policies__policy_id__deactivate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Search */
    post: operations['search_api_v1_search_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/policies/{policy_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Policy */
    get: operations['read_policy_api_v1_policies__policy_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/policies/{policy_id}/sources/{source_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Original Source */
    get: operations['read_original_source_api_v1_policies__policy_id__sources__source_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/assistant/answer': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Answer */
    post: operations['answer_api_v1_assistant_answer_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/assistant/answer/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Answer Events
     * @description Streams truthful status events; answer content appears only in the final verified event.
     */
    post: operations['answer_events_api_v1_assistant_answer_events_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/operations/metrics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Metrics */
    get: operations['metrics_api_v1_admin_operations_metrics_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/operations/retrieval-telemetry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieval Telemetry */
    get: operations['retrieval_telemetry_api_v1_admin_operations_retrieval_telemetry_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/speech/capabilities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Speech Capabilities */
    get: operations['speech_capabilities_api_v1_speech_capabilities_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/speech/transcribe': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transcribe Speech */
    post: operations['transcribe_speech_api_v1_speech_transcribe_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccessDimension */
    AccessDimension: {
      mode: components['schemas']['AccessMode'];
      /** Values */
      values?: string[];
    };
    /**
     * AccessMode
     * @enum {string}
     */
    AccessMode: 'all' | 'selected';
    /** AccessScope */
    AccessScope: {
      departments: components['schemas']['AccessDimension'];
      locations: components['schemas']['AccessDimension'];
      roles: components['schemas']['AccessDimension'];
    };
    /** AccessUpdateRequest */
    AccessUpdateRequest: {
      access: components['schemas']['AccessScope'];
    };
    /** AssistantCitation */
    AssistantCitation: {
      /** Chunk Id */
      chunk_id: string;
      /** Policy Id */
      policy_id: string;
      /** Policy Title */
      policy_title: string;
      /** Section Id */
      section_id: string;
      /** Heading Path */
      heading_path: string[];
      /** Document Id */
      document_id: string;
      source: components['schemas']['SourceLocator'];
    };
    /** AssistantRequest */
    AssistantRequest: {
      /** Question */
      question: string;
      language: components['schemas']['Language'];
      /** Session Id */
      session_id?: string | null;
    };
    /**
     * BlockKind
     * @enum {string}
     */
    BlockKind: 'paragraph' | 'ordered_list' | 'unordered_list' | 'table';
    /** Body_transcribe_speech_api_v1_speech_transcribe_post */
    Body_transcribe_speech_api_v1_speech_transcribe_post: {
      /** Audio */
      audio: string;
    };
    /** Body_upload_source_api_v1_admin_sources_upload_post */
    Body_upload_source_api_v1_admin_sources_upload_post: {
      /** Policy Id */
      policy_id: string;
      /** Version Id */
      version_id: string;
      source_format: components['schemas']['SourceFormat'];
      /** File */
      file: string;
    };
    /** BoundingBox */
    BoundingBox: {
      /** X */
      x: number;
      /** Y */
      y: number;
      /** Width */
      width: number;
      /** Height */
      height: number;
      /**
       * Unit
       * @default normalized
       */
      unit: string;
    };
    /** CanonicalBlock */
    'CanonicalBlock-Input': {
      /** Id */
      id: string;
      kind: components['schemas']['BlockKind'];
      /** Text */
      text?: string | null;
      /** List Items */
      list_items?: components['schemas']['CanonicalListItem-Input'][];
      table?: components['schemas']['CanonicalTable'] | null;
      source: components['schemas']['SourceLocator'];
    };
    /** CanonicalBlock */
    'CanonicalBlock-Output': {
      /** Id */
      id: string;
      kind: components['schemas']['BlockKind'];
      /** Text */
      text?: string | null;
      /** List Items */
      list_items?: components['schemas']['CanonicalListItem-Output'][];
      table?: components['schemas']['CanonicalTable'] | null;
      source: components['schemas']['SourceLocator'];
    };
    /** CanonicalListItem */
    'CanonicalListItem-Input': {
      /** Text */
      text: string;
      /**
       * Level
       * @default 0
       */
      level: number;
      /** Marker */
      marker?: string | null;
      /** Children */
      children?: components['schemas']['CanonicalListItem-Input'][];
      source: components['schemas']['SourceLocator'];
    };
    /** CanonicalListItem */
    'CanonicalListItem-Output': {
      /** Text */
      text: string;
      /**
       * Level
       * @default 0
       */
      level: number;
      /** Marker */
      marker?: string | null;
      /** Children */
      children?: components['schemas']['CanonicalListItem-Output'][];
      source: components['schemas']['SourceLocator'];
    };
    /** CanonicalSOP */
    'CanonicalSOP-Input': {
      /** Organization Id */
      organization_id: string;
      /**
       * Schema Version
       * @default 1.0
       */
      schema_version: string;
      /** Id */
      id: string;
      /** Policy Id */
      policy_id: string;
      /** Version Id */
      version_id: string;
      /** Source Document Ids */
      source_document_ids: string[];
      /** Title */
      title: string;
      /** Policy Number */
      policy_number?: string | null;
      /** Sections */
      sections: components['schemas']['CanonicalSection-Input'][];
      /** Review Revisions */
      review_revisions?: components['schemas']['ReviewRevision'][];
      /**
       * Approved
       * @default false
       */
      approved: boolean;
      /** Approved At */
      approved_at?: string | null;
    };
    /** CanonicalSOP */
    'CanonicalSOP-Output': {
      /** Organization Id */
      organization_id: string;
      /**
       * Schema Version
       * @default 1.0
       */
      schema_version: string;
      /** Id */
      id: string;
      /** Policy Id */
      policy_id: string;
      /** Version Id */
      version_id: string;
      /** Source Document Ids */
      source_document_ids: string[];
      /** Title */
      title: string;
      /** Policy Number */
      policy_number?: string | null;
      /** Sections */
      sections: components['schemas']['CanonicalSection-Output'][];
      /** Review Revisions */
      review_revisions?: components['schemas']['ReviewRevision'][];
      /**
       * Approved
       * @default false
       */
      approved: boolean;
      /** Approved At */
      approved_at?: string | null;
    };
    /** CanonicalSection */
    'CanonicalSection-Input': {
      /** Id */
      id: string;
      /** Stable Key */
      stable_key: string;
      /** Policy Number */
      policy_number?: string | null;
      /** Chapter */
      chapter?: string | null;
      /** Heading */
      heading: string;
      /** Heading Level */
      heading_level: number;
      /** Parent Section Id */
      parent_section_id?: string | null;
      /** Heading Path */
      heading_path: string[];
      /** Blocks */
      blocks: components['schemas']['CanonicalBlock-Input'][];
      access: components['schemas']['AccessScope'];
      source: components['schemas']['SourceLocator'];
      /** Content Hash */
      content_hash: string;
    };
    /** CanonicalSection */
    'CanonicalSection-Output': {
      /** Id */
      id: string;
      /** Stable Key */
      stable_key: string;
      /** Policy Number */
      policy_number?: string | null;
      /** Chapter */
      chapter?: string | null;
      /** Heading */
      heading: string;
      /** Heading Level */
      heading_level: number;
      /** Parent Section Id */
      parent_section_id?: string | null;
      /** Heading Path */
      heading_path: string[];
      /** Blocks */
      blocks: components['schemas']['CanonicalBlock-Output'][];
      access: components['schemas']['AccessScope'];
      source: components['schemas']['SourceLocator'];
      /** Content Hash */
      content_hash: string;
    };
    /** CanonicalTable */
    CanonicalTable: {
      /** Caption */
      caption?: string | null;
      /** Cells */
      cells: components['schemas']['CanonicalTableCell'][];
      source: components['schemas']['SourceLocator'];
    };
    /** CanonicalTableCell */
    CanonicalTableCell: {
      /** Row */
      row: number;
      /** Column */
      column: number;
      /** Text */
      text: string;
      /**
       * Row Span
       * @default 1
       */
      row_span: number;
      /**
       * Column Span
       * @default 1
       */
      column_span: number;
      /**
       * Is Header
       * @default false
       */
      is_header: boolean;
      source: components['schemas']['SourceLocator'];
    };
    /** CreatePolicyRequest */
    CreatePolicyRequest: {
      /** Title */
      title: string;
      /** Category */
      category: string;
      /** Policy Number */
      policy_number?: string | null;
      /** Version Label */
      version_label: string;
      /** Effective Date */
      effective_date?: string | null;
      access: components['schemas']['AccessScope'];
    };
    /** DuplicateSectionGroup */
    DuplicateSectionGroup: {
      /** Organization Id */
      organization_id: string;
      /** Content Hash */
      content_hash: string;
      /** Occurrences */
      occurrences: components['schemas']['DuplicateSectionOccurrence'][];
    };
    /** DuplicateSectionOccurrence */
    DuplicateSectionOccurrence: {
      /** Source Document Id */
      source_document_id: string;
      /** Section Id */
      section_id: string;
      /** Heading */
      heading: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** IngestionEvent */
    IngestionEvent: {
      /** Organization Id */
      organization_id: string;
      state: components['schemas']['IngestionState'];
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at?: string;
      /** Detail */
      detail: string;
    };
    /** IngestionJob */
    IngestionJob: {
      /** Organization Id */
      organization_id: string;
      /** Id */
      id: string;
      /** Source Document Id */
      source_document_id: string;
      /** Version Id */
      version_id: string;
      state: components['schemas']['IngestionState'];
      /** Events */
      events: components['schemas']['IngestionEvent'][];
      /**
       * Retry Count
       * @default 0
       */
      retry_count: number;
      /** Error Code */
      error_code?: string | null;
    };
    /**
     * IngestionState
     * @enum {string}
     */
    IngestionState:
      | 'uploaded'
      | 'extracting'
      | 'structuring'
      | 'review_required'
      | 'structure_approved'
      | 'chunking'
      | 'embedding'
      | 'indexing'
      | 'verifying'
      | 'ready_for_review'
      | 'published'
      | 'failed';
    /**
     * Language
     * @enum {string}
     */
    Language: 'english' | 'urdu' | 'roman_urdu';
    /** PasteSourceRequest */
    PasteSourceRequest: {
      /** Policy Id */
      policy_id: string;
      /** Version Id */
      version_id: string;
      /** Title */
      title: string;
      /** Content */
      content: string;
      source_format: components['schemas']['SourceFormat'];
    };
    /** PolicyReaderDocument */
    PolicyReaderDocument: {
      /** Policy Id */
      policy_id: string;
      /** Title */
      title: string;
      /** Category */
      category: string;
      /** Version Label */
      version_label: string;
      /** Sections */
      sections: components['schemas']['PolicyReaderSection'][];
      /** Original Download Allowed */
      original_download_allowed: boolean;
    };
    /** PolicyReaderSection */
    PolicyReaderSection: {
      /** Organization Id */
      organization_id: string;
      /** Policy Id */
      policy_id: string;
      /** Version Id */
      version_id: string;
      /** Section Id */
      section_id: string;
      /** Heading */
      heading: string;
      /** Heading Path */
      heading_path: string[];
      /** Policy Number */
      policy_number?: string | null;
      /** Content */
      content: string;
      source: components['schemas']['SourceLocator'];
    };
    /**
     * PolicyStatus
     * @enum {string}
     */
    PolicyStatus: 'draft' | 'active' | 'inactive';
    /** ReviewConfirmationRequest */
    ReviewConfirmationRequest: {
      /** Confirmed */
      confirmed: boolean;
    };
    /** ReviewRevision */
    ReviewRevision: {
      /** Revision */
      revision: number;
      /** Reviewer Id */
      reviewer_id: string;
      /** Note */
      note?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
    };
    /** ReviewUpdate */
    ReviewUpdate: {
      canonical: components['schemas']['CanonicalSOP-Input'];
    };
    /** SOPPolicy */
    SOPPolicy: {
      /** Organization Id */
      organization_id: string;
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Category */
      category: string;
      /** Policy Number */
      policy_number?: string | null;
      /** @default draft */
      status: components['schemas']['PolicyStatus'];
      /** Active Version Id */
      active_version_id?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at?: string;
    };
    /** SOPVersion */
    SOPVersion: {
      /** Organization Id */
      organization_id: string;
      /** Id */
      id: string;
      /** Policy Id */
      policy_id: string;
      /** Version Label */
      version_label: string;
      /** Effective Date */
      effective_date?: string | null;
      /** @default draft */
      status: components['schemas']['VersionStatus'];
      access: components['schemas']['AccessScope'];
      /** Source Document Ids */
      source_document_ids?: string[];
      /** Canonical Document Ids */
      canonical_document_ids?: string[];
      /** Index Revision */
      index_revision?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
      /** Published At */
      published_at?: string | null;
    };
    /** SearchEvidence */
    SearchEvidence: {
      /** Organization Id */
      organization_id: string;
      /** Chunk Id */
      chunk_id: string;
      /** Policy Id */
      policy_id: string;
      /** Version Id */
      version_id: string;
      /** Section Id */
      section_id: string;
      /** Policy Title */
      policy_title: string;
      /** Heading Path */
      heading_path: string[];
      /** Policy Number */
      policy_number?: string | null;
      /** Excerpt */
      excerpt: string;
      source: components['schemas']['SourceLocator'];
      /** Fused Score */
      fused_score: number;
    };
    /** SearchRequest */
    SearchRequest: {
      /** Query */
      query: string;
      /** @default english */
      language: components['schemas']['Language'];
      /**
       * Limit
       * @default 8
       */
      limit: number;
    };
    /** SearchResponse */
    SearchResponse: {
      /** Results */
      results: components['schemas']['SearchEvidence'][];
      /** Query */
      query: string;
      language: components['schemas']['Language'];
    };
    /** SectionChange */
    SectionChange: {
      /** Organization Id */
      organization_id: string;
      kind: components['schemas']['SectionChangeKind'];
      /** Stable Key */
      stable_key: string;
      /** Heading */
      heading: string;
      /** Old Content */
      old_content?: string | null;
      /** New Content */
      new_content?: string | null;
      /**
       * Access Changed
       * @default false
       */
      access_changed: boolean;
    };
    /**
     * SectionChangeKind
     * @enum {string}
     */
    SectionChangeKind: 'added' | 'removed' | 'changed';
    /** SourceDocument */
    SourceDocument: {
      /** Organization Id */
      organization_id: string;
      /** Id */
      id: string;
      /** Policy Id */
      policy_id: string;
      /** Version Id */
      version_id: string;
      /** File Name */
      file_name: string;
      /** Media Type */
      media_type: string;
      source_format: components['schemas']['SourceFormat'];
      /** Sha256 */
      sha256: string;
      /** Original Artifact Uri */
      original_artifact_uri: string;
      /** @default uploaded */
      status: components['schemas']['SourceStatus'];
      /** Parser Provider */
      parser_provider?: string | null;
      /** Parser Version */
      parser_version?: string | null;
      /** Raw Artifact Uri */
      raw_artifact_uri?: string | null;
      /** Canonical Artifact Uri */
      canonical_artifact_uri?: string | null;
      /** Reviewed Artifact Uri */
      reviewed_artifact_uri?: string | null;
      /** Error Code */
      error_code?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
    };
    /**
     * SourceFormat
     * @enum {string}
     */
    SourceFormat:
      | 'pdf'
      | 'scanned_pdf'
      | 'image'
      | 'docx'
      | 'xlsx'
      | 'markdown'
      | 'structured_text';
    /** SourceLocator */
    SourceLocator: {
      /** Source Document Id */
      source_document_id: string;
      /** Page Start */
      page_start?: number | null;
      /** Page End */
      page_end?: number | null;
      /**
       * Bounding Boxes
       * @default []
       */
      bounding_boxes: components['schemas']['BoundingBox'][];
      /** Text Start */
      text_start?: number | null;
      /** Text End */
      text_end?: number | null;
      /** Sheet Name */
      sheet_name?: string | null;
      /** Cell Range */
      cell_range?: string | null;
      /** Block Anchor */
      block_anchor?: string | null;
    };
    /**
     * SourceStatus
     * @enum {string}
     */
    SourceStatus:
      'uploaded' | 'processing' | 'review_required' | 'approved' | 'failed';
    /** SpeechTranscription */
    SpeechTranscription: {
      /** Detected Language */
      detected_language: string;
      /** Raw Transcript */
      raw_transcript: string;
      /** Normalized Transcript */
      normalized_transcript: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VerifiedAnswer */
    VerifiedAnswer: {
      /** Organization Id */
      organization_id: string;
      /** Answerable */
      answerable: boolean;
      /** Answer */
      answer: string;
      language: components['schemas']['Language'];
      /** Citations */
      citations: components['schemas']['AssistantCitation'][];
      /** Verified */
      verified: boolean;
      /** Session Id */
      session_id: string;
    };
    /**
     * VersionStatus
     * @enum {string}
     */
    VersionStatus:
      | 'draft'
      | 'extraction_review'
      | 'ready_for_indexing'
      | 'indexing'
      | 'ready_to_publish'
      | 'published'
      | 'superseded'
      | 'failed';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_profile_api_v1_profile_me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_language_api_v1_profile_language_put: {
    parameters: {
      query: {
        language: components['schemas']['Language'];
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  capabilities_api_v1_admin_sources_capabilities_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_source_api_v1_admin_sources_upload_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_source_api_v1_admin_sources_upload_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SourceDocument'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  paste_source_api_v1_admin_sources_paste_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasteSourceRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SourceDocument'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_review_api_v1_admin_sources__source_id__review_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_review_api_v1_admin_sources__source_id__review_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CanonicalSOP-Output'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_original_api_v1_admin_sources__source_id__original_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_job_api_v1_admin_sources__source_id__job_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IngestionJob'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  retry_source_api_v1_admin_sources__source_id__retry_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SourceDocument'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_policies_api_v1_admin_policies_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_policy_api_v1_admin_policies_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePolicyRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  policy_viewer_api_v1_admin_policies__policy_id__viewer_get: {
    parameters: {
      query?: {
        version_id?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        policy_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_access_api_v1_admin_versions__version_id__access_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccessUpdateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SOPVersion'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  approve_structure_api_v1_admin_sources__source_id__approve_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewConfirmationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SOPVersion'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  prepare_publication_api_v1_admin_versions__version_id__prepare_publication_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SOPVersion'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  publish_version_api_v1_admin_versions__version_id__publish_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SOPVersion'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  rollback_version_api_v1_admin_policies__policy_id__rollback__version_id__post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        policy_id: string;
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SOPVersion'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  version_diff_api_v1_admin_versions__version_id__diff_get: {
    parameters: {
      query: {
        against: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SectionChange'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  duplicate_sections_api_v1_admin_versions__version_id__duplicates_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DuplicateSectionGroup'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  deactivate_policy_api_v1_admin_policies__policy_id__deactivate_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        policy_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SOPPolicy'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  search_api_v1_search_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SearchRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_policy_api_v1_policies__policy_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        policy_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PolicyReaderDocument'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_original_source_api_v1_policies__policy_id__sources__source_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        policy_id: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  answer_api_v1_assistant_answer_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssistantRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VerifiedAnswer'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  answer_events_api_v1_assistant_answer_events_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssistantRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  metrics_api_v1_admin_operations_metrics_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  retrieval_telemetry_api_v1_admin_operations_retrieval_telemetry_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  speech_capabilities_api_v1_speech_capabilities_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  transcribe_speech_api_v1_speech_transcribe_post: {
    parameters: {
      query: {
        response_language: components['schemas']['Language'];
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_transcribe_speech_api_v1_speech_transcribe_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SpeechTranscription'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
}
