import { useLanguage } from '../language/useLanguage';
import { sourceLabel } from './policyPresentation';

const english = {
  navLibrary: 'Policy Library',
  navUpload: 'Upload SOP',
  navReview: 'Review Queue',
  management: 'Document management',
  loadingSops: 'Loading SOPs',
  libraryIntro:
    'View and manage organizational SOPs within your administrative scope.',
  addSop: 'Add SOP',
  search: 'Search title, policy number, or document name',
  status: 'Status',
  versionLabel: 'Version',
  noVersion: 'No version',
  scannedPdf: 'Scanned PDF',
  image: 'Image',
  structuredText: 'Text',
  allStatuses: 'All statuses',
  department: 'Department',
  allDepartments: 'All departments',
  sourceType: 'Source Type',
  allTypes: 'All types',
  updated: 'Updated',
  anyTime: 'Any time',
  past30: 'Past 30 days',
  past90: 'Past 90 days',
  sort: 'Sort',
  sops: 'SOPs',
  document: 'document',
  documents: 'documents',
  sections: 'sections',
  pages: 'pages',
  open: 'Open',
  updatedOn: 'Updated',
  processingFailed: 'Processing failed',
  openDetails: 'Open for details',
  noSops: 'No SOPs have been added yet',
  noSopsDetail: 'Add your first document to build the policy library.',
  noMatches: 'No matching SOPs',
  noMatchesDetail: 'Try another search or adjust the filters.',
  clearFilters: 'Clear filters',
  libraryUnavailable: 'Policy library unavailable',
  libraryError:
    'The authorized SOP list could not be loaded. Please try again.',
  adminRequired: 'Administrative access required',
  adminRequiredDetail: 'Your account is not assigned to SOP administration.',
  sopUnavailable: 'SOP unavailable',
  sopCouldNotOpen: 'SOP could not be opened',
  sopUnavailableDetail:
    'This document may be outside your administrative scope or no longer available.',
  organizationalSop: 'Organizational SOP',
  noSource: 'No source uploaded',
  current: 'Current',
  reviewExtraction: 'Review extraction',
  reviewSource: 'Review source',
  versionWorkflow: 'Version workflow',
  content: 'Content',
  original: 'Original Document',
  details: 'Details',
  versions: 'Versions',
  failedHelp: 'Processing failed.',
  inspectSource: 'Inspect the source and version details.',
  documentInformation: 'Document information',
  sopTitle: 'SOP title',
  policyNumber: 'Policy number',
  sourceDocument: 'Source document',
  currentSelection: 'Current selection',
  created: 'Created',
  accessScope: 'Access scope',
  pageCount: 'Page count',
  sectionCount: 'Section count',
  versionHistory: 'Version history',
  versionHint:
    'Select an older version to inspect its content and original in read-only mode.',
  publishedOn: 'Published',
  selected: 'Selected',
  all: 'All',
  departments: 'departments',
  locations: 'locations',
  roles: 'roles',
  privateOriginal: 'Private original',
  downloadOriginal: 'Download original',
  originalRestricted:
    'This original contains content outside your management scope or has not been reviewed. Open extraction review if authorized.',
  originalLoading: 'Loading original document',
  originalUnavailable: 'The original could not be loaded. Please try again.',
  previewUnavailable:
    'Preview is unavailable for this format. Use Download original to inspect the file in its native application.',
  noOriginal: 'No original file is attached to this version.',
  contents: 'Contents',
  section: 'section',
  sectionsControl: 'Sections',
  of: 'of',
  expand: 'Expand',
  collapse: 'Collapse',
  sopContent: 'SOP content',
  policy: 'Policy',
  sourcePage: 'Source: Page',
  sourceSheet: 'Source',
  previousSection: 'Previous section',
  nextSection: 'Next section',
  structuredUnavailable:
    'Structured content is not available yet. Open extraction review once processing completes.',
  structuredFailed:
    'Processing failed. Review the source or retry processing if authorized.',
  statusPublished: 'Published',
  statusDraft: 'Draft',
  statusProcessing: 'Processing',
  statusReviewRequired: 'Review Required',
  statusReady: 'Ready for Review',
  statusFailed: 'Failed',
  statusSuperseded: 'Superseded',
  sortRecent: 'Recently Updated',
  sortTitle: 'Title A–Z',
  sortVersion: 'Newest Version',
  sortStatus: 'Status',
  backToLibrary: 'Back to library',
  reviewTitle: 'Review extracted structure',
  reviewLead:
    'Correct OCR and structure on the right. The original source remains unchanged.',
  humanReviewRequired: 'Human review required',
  originalSource: 'Original source',
  privateLabel: 'Private',
  sourceLocationHint: 'Source locations follow the selected canonical block.',
  canonicalSop: 'Canonical SOP',
  structuredSopContents: 'Structured SOP contents',
  heading: 'Heading',
  level: 'Level',
  item: 'Item',
  tableCells: 'Table cells',
  addSectionAfter: 'Add section after',
  newSection: 'New section',
  reviewingAs: 'Reviewing as',
  systemAdministrator: 'System Administrator',
  sopAdministrator: 'SOP Administrator',
  confirmCompared:
    'I confirm that I compared this content with the original source.',
  indexVerified: 'Index verified — ready to publish',
  structureApproved: 'Structure approved',
  correctionsSaved: 'Corrections saved',
  saveCorrection: 'Save correction',
  submitReview: 'Submit review',
  prepareSearchIndex: 'Prepare search index',
  publish: 'Publish',
  reviewUnavailable: 'Review unavailable',
  reviewUnavailableDetail:
    'The source may be outside your scope, unavailable, or the API may be offline.',
  extractionUnavailable: 'Extraction unavailable',
  extractionUnavailableDetail:
    'This format requires a configured parser provider before canonical review.',
  originalStructuredView: 'Original structured view',
  orderedList: 'Numbered list',
  unorderedList: 'Bullet list',
};
type Copy = { [K in keyof typeof english]: string };
const urdu: Copy = {
  navLibrary: 'پالیسی لائبریری',
  navUpload: 'ایس او پی اپ لوڈ کریں',
  navReview: 'نظرثانی کی فہرست',
  management: 'دستاویزات کا انتظام',
  loadingSops: 'ایس او پیز کھل رہی ہیں',
  libraryIntro:
    'اپنے انتظامی دائرے میں تنظیمی ایس او پیز دیکھیں اور ان کا انتظام کریں۔',
  addSop: 'ایس او پی شامل کریں',
  search: 'عنوان، پالیسی نمبر یا دستاویز کے نام سے تلاش کریں',
  status: 'حالت',
  versionLabel: 'نسخہ',
  noVersion: 'کوئی نسخہ نہیں',
  scannedPdf: 'اسکین شدہ PDF',
  image: 'تصویر',
  structuredText: 'متن',
  allStatuses: 'تمام حالتیں',
  department: 'شعبہ',
  allDepartments: 'تمام شعبے',
  sourceType: 'دستاویز کی قسم',
  allTypes: 'تمام اقسام',
  updated: 'تازہ کاری',
  anyTime: 'کسی بھی وقت',
  past30: 'گزشتہ ۳۰ دن',
  past90: 'گزشتہ ۹۰ دن',
  sort: 'ترتیب',
  sops: 'ایس او پیز',
  document: 'دستاویز',
  documents: 'دستاویزات',
  sections: 'حصے',
  pages: 'صفحات',
  open: 'کھولیں',
  updatedOn: 'تازہ کاری',
  processingFailed: 'پروسیسنگ ناکام',
  openDetails: 'تفصیلات دیکھیں',
  noSops: 'ابھی کوئی ایس او پی شامل نہیں کی گئی',
  noSopsDetail: 'پالیسی لائبریری شروع کرنے کے لیے پہلی دستاویز شامل کریں۔',
  noMatches: 'کوئی مماثل ایس او پی نہیں ملی',
  noMatchesDetail: 'دوسری تلاش کریں یا فلٹر بدلیں۔',
  clearFilters: 'فلٹر صاف کریں',
  libraryUnavailable: 'پالیسی لائبریری دستیاب نہیں',
  libraryError:
    'آپ کے لیے دستیاب ایس او پیز کی فہرست نہیں کھل سکی۔ دوبارہ کوشش کریں۔',
  adminRequired: 'انتظامی رسائی درکار ہے',
  adminRequiredDetail: 'آپ کا اکاؤنٹ ایس او پی انتظام کے لیے مقرر نہیں ہے۔',
  sopUnavailable: 'ایس او پی دستیاب نہیں',
  sopCouldNotOpen: 'ایس او پی نہیں کھل سکی',
  sopUnavailableDetail:
    'یہ دستاویز آپ کے انتظامی دائرے سے باہر یا اب دستیاب نہیں ہو سکتی۔',
  organizationalSop: 'تنظیمی ایس او پی',
  noSource: 'کوئی ماخذ اپ لوڈ نہیں کیا گیا',
  current: 'موجودہ',
  reviewExtraction: 'اخذ کردہ مواد کا جائزہ',
  reviewSource: 'ماخذ کا جائزہ',
  versionWorkflow: 'نسخوں کا عمل',
  content: 'مواد',
  original: 'اصل دستاویز',
  details: 'تفصیلات',
  versions: 'نسخے',
  failedHelp: 'پروسیسنگ ناکام ہو گئی۔',
  inspectSource: 'ماخذ اور نسخے کی تفصیلات دیکھیں۔',
  documentInformation: 'دستاویز کی معلومات',
  sopTitle: 'ایس او پی کا عنوان',
  policyNumber: 'پالیسی نمبر',
  sourceDocument: 'ماخذ دستاویز',
  currentSelection: 'منتخب نسخہ',
  created: 'تخلیق کی تاریخ',
  accessScope: 'رسائی کا دائرہ',
  pageCount: 'صفحات کی تعداد',
  sectionCount: 'حصوں کی تعداد',
  versionHistory: 'نسخوں کی تاریخ',
  versionHint: 'پرانے نسخے کا مواد اور اصل دستاویز صرف دیکھنے کے لیے کھولیں۔',
  publishedOn: 'شائع ہوا',
  selected: 'منتخب',
  all: 'تمام',
  departments: 'شعبے',
  locations: 'مقامات',
  roles: 'کردار',
  privateOriginal: 'محفوظ اصل',
  downloadOriginal: 'اصل ڈاؤن لوڈ کریں',
  originalRestricted:
    'اس اصل میں آپ کے انتظامی دائرے سے باہر مواد ہے یا اس کا جائزہ نہیں لیا گیا۔ اجازت ہو تو اخذ کردہ مواد کا جائزہ کھولیں۔',
  originalLoading: 'اصل دستاویز کھل رہی ہے',
  originalUnavailable: 'اصل دستاویز نہیں کھل سکی۔ دوبارہ کوشش کریں۔',
  previewUnavailable:
    'اس قسم کا پیش منظر دستیاب نہیں۔ اصل فائل کو اس کے متعلقہ پروگرام میں دیکھنے کے لیے ڈاؤن لوڈ کریں۔',
  noOriginal: 'اس نسخے کے ساتھ کوئی اصل فائل منسلک نہیں۔',
  contents: 'فہرست',
  section: 'حصہ',
  sectionsControl: 'حصے',
  of: 'از',
  expand: 'کھولیں',
  collapse: 'سمیٹیں',
  sopContent: 'ایس او پی کا مواد',
  policy: 'پالیسی',
  sourcePage: 'ماخذ: صفحہ',
  sourceSheet: 'ماخذ',
  previousSection: 'پچھلا حصہ',
  nextSection: 'اگلا حصہ',
  structuredUnavailable:
    'منظم مواد ابھی دستیاب نہیں۔ پروسیسنگ مکمل ہونے پر اخذ کردہ مواد کا جائزہ کھولیں۔',
  structuredFailed:
    'پروسیسنگ ناکام ہو گئی۔ اجازت ہو تو ماخذ دیکھیں یا دوبارہ کوشش کریں۔',
  statusPublished: 'شائع شدہ',
  statusDraft: 'مسودہ',
  statusProcessing: 'پروسیسنگ',
  statusReviewRequired: 'نظرثانی درکار',
  statusReady: 'نظرثانی کے لیے تیار',
  statusFailed: 'ناکام',
  statusSuperseded: 'پرانا نسخہ',
  sortRecent: 'حالیہ تازہ کاری',
  sortTitle: 'عنوان الف سے ے',
  sortVersion: 'تازہ ترین نسخہ',
  sortStatus: 'حالت',
  backToLibrary: 'لائبریری پر واپس جائیں',
  reviewTitle: 'اخذ کردہ ساخت کا جائزہ',
  reviewLead: 'دائیں طرف OCR اور ساخت درست کریں۔ اصل ماخذ تبدیل نہیں ہوگا۔',
  humanReviewRequired: 'انسانی جائزہ درکار ہے',
  originalSource: 'اصل ماخذ',
  privateLabel: 'محفوظ',
  sourceLocationHint: 'ماخذ کے مقامات منتخب منظم حصے کے مطابق ہیں۔',
  canonicalSop: 'منظم ایس او پی',
  structuredSopContents: 'منظم ایس او پی کی فہرست',
  heading: 'عنوان',
  level: 'درجہ',
  item: 'نکتہ',
  tableCells: 'جدول کے خانے',
  addSectionAfter: 'اس کے بعد حصہ شامل کریں',
  newSection: 'نیا حصہ',
  reviewingAs: 'جائزہ لینے والا',
  systemAdministrator: 'سسٹم منتظم',
  sopAdministrator: 'ایس او پی منتظم',
  confirmCompared:
    'میں تصدیق کرتا ہوں کہ میں نے اس مواد کا اصل ماخذ سے موازنہ کیا ہے۔',
  indexVerified: 'اشاریہ تصدیق شدہ — اشاعت کے لیے تیار',
  structureApproved: 'ساخت منظور ہو گئی',
  correctionsSaved: 'درستگیاں محفوظ ہو گئیں',
  saveCorrection: 'درستگی محفوظ کریں',
  submitReview: 'جائزہ جمع کریں',
  prepareSearchIndex: 'تلاش کا اشاریہ تیار کریں',
  publish: 'شائع کریں',
  reviewUnavailable: 'جائزہ دستیاب نہیں',
  reviewUnavailableDetail:
    'ماخذ آپ کے دائرے سے باہر، دستیاب نہیں، یا API آف لائن ہو سکتی ہے۔',
  extractionUnavailable: 'اخذ کردہ مواد دستیاب نہیں',
  extractionUnavailableDetail:
    'منظم جائزے سے پہلے اس قسم کے لیے parser provider درکار ہے۔',
  originalStructuredView: 'اصل منظم منظر',
  orderedList: 'نمبر وار فہرست',
  unorderedList: 'بلٹ فہرست',
};
const roman_urdu: Copy = {
  navLibrary: 'Policy Library',
  navUpload: 'SOP upload karein',
  navReview: 'Review Queue',
  management: 'Dastavezat ka intizam',
  loadingSops: 'SOPs khul rahi hain',
  libraryIntro:
    'Apne intizami daire mein tanzeemi SOPs dekhein aur manage karein.',
  addSop: 'SOP shamil karein',
  search: 'Unwan, policy number ya document naam se talash karein',
  status: 'Haalat',
  versionLabel: 'Version',
  noVersion: 'Koi version nahin',
  scannedPdf: 'Scan ki hui PDF',
  image: 'Tasveer',
  structuredText: 'Matn',
  allStatuses: 'Tamam haalatein',
  department: 'Shoba',
  allDepartments: 'Tamam shobay',
  sourceType: 'Source ki qisam',
  allTypes: 'Tamam qisamain',
  updated: 'Update',
  anyTime: 'Kisi bhi waqt',
  past30: 'Pichlay 30 din',
  past90: 'Pichlay 90 din',
  sort: 'Tarteeb',
  sops: 'SOPs',
  document: 'document',
  documents: 'documents',
  sections: 'sections',
  pages: 'pages',
  open: 'Kholein',
  updatedOn: 'Update',
  processingFailed: 'Processing nakam',
  openDetails: 'Tafseel dekhein',
  noSops: 'Abhi koi SOP shamil nahin hui',
  noSopsDetail:
    'Policy Library shuru karne ke liye pehla document shamil karein.',
  noMatches: 'Koi milti SOP nahin mili',
  noMatchesDetail: 'Doosri talash karein ya filters badlein.',
  clearFilters: 'Filters saaf karein',
  libraryUnavailable: 'Policy Library dastiyab nahin',
  libraryError:
    'Aap ke liye dastiyab SOPs ki fehrist nahin khul saki. Dobara koshish karein.',
  adminRequired: 'Admin rasai darkar hai',
  adminRequiredDetail:
    'Aap ka account SOP administration ke liye muqarrar nahin.',
  sopUnavailable: 'SOP dastiyab nahin',
  sopCouldNotOpen: 'SOP nahin khul saki',
  sopUnavailableDetail:
    'Yeh document aap ke admin daire se bahar ya ab dastiyab nahin ho sakta.',
  organizationalSop: 'Tanzeemi SOP',
  noSource: 'Koi source upload nahin hua',
  current: 'Maujooda',
  reviewExtraction: 'Extraction review karein',
  reviewSource: 'Source review karein',
  versionWorkflow: 'Version workflow',
  content: 'Content',
  original: 'Asal document',
  details: 'Tafseel',
  versions: 'Versions',
  failedHelp: 'Processing nakam hui.',
  inspectSource: 'Source aur version ki tafseel dekhein.',
  documentInformation: 'Document ki maloomat',
  sopTitle: 'SOP ka unwan',
  policyNumber: 'Policy number',
  sourceDocument: 'Source document',
  currentSelection: 'Chuna hua version',
  created: 'Banaya gaya',
  accessScope: 'Rasai ka daira',
  pageCount: 'Safhon ki tadaad',
  sectionCount: 'Sections ki tadaad',
  versionHistory: 'Versions ki tareekh',
  versionHint:
    'Purana version sirf parhne ke liye kholein aur us ka content aur asal file dekhein.',
  publishedOn: 'Published',
  selected: 'Chunay hue',
  all: 'Tamam',
  departments: 'shobay',
  locations: 'locations',
  roles: 'roles',
  privateOriginal: 'Mehfooz asal',
  downloadOriginal: 'Asal download karein',
  originalRestricted:
    'Is asal mein aap ke admin daire se bahar content hai ya review nahin hua. Ijazat ho to extraction review kholein.',
  originalLoading: 'Asal document khul raha hai',
  originalUnavailable: 'Asal document nahin khul saka. Dobara koshish karein.',
  previewUnavailable:
    'Is format ka preview dastiyab nahin. Native app mein dekhne ke liye asal file download karein.',
  noOriginal: 'Is version ke saath koi asal file nahin lagi.',
  contents: 'Fehrist',
  section: 'section',
  sectionsControl: 'Sections',
  of: 'mein se',
  expand: 'Kholein',
  collapse: 'Band karein',
  sopContent: 'SOP content',
  policy: 'Policy',
  sourcePage: 'Source: Page',
  sourceSheet: 'Source',
  previousSection: 'Pichla section',
  nextSection: 'Agla section',
  structuredUnavailable:
    'Structured content abhi dastiyab nahin. Processing ke baad extraction review kholein.',
  structuredFailed:
    'Processing nakam hui. Ijazat ho to source dekhein ya dobara koshish karein.',
  statusPublished: 'Published',
  statusDraft: 'Draft',
  statusProcessing: 'Processing',
  statusReviewRequired: 'Review darkar',
  statusReady: 'Review ke liye tayyar',
  statusFailed: 'Nakam',
  statusSuperseded: 'Purana version',
  sortRecent: 'Haal hi mein update',
  sortTitle: 'Unwan A–Z',
  sortVersion: 'Naya version',
  sortStatus: 'Haalat',
  backToLibrary: 'Library par wapas jayein',
  reviewTitle: 'Extract ki hui structure review karein',
  reviewLead:
    'Dahni taraf OCR aur structure durust karein. Asal source tabdeel nahin hoga.',
  humanReviewRequired: 'Insani review darkar hai',
  originalSource: 'Asal source',
  privateLabel: 'Mehfooz',
  sourceLocationHint:
    'Source locations chunay hue canonical block ke mutabiq hain.',
  canonicalSop: 'Canonical SOP',
  structuredSopContents: 'Structured SOP ki fehrist',
  heading: 'Unwan',
  level: 'Darja',
  item: 'Nuqta',
  tableCells: 'Table cells',
  addSectionAfter: 'Is ke baad section shamil karein',
  newSection: 'Naya section',
  reviewingAs: 'Review kar rahe hain',
  systemAdministrator: 'System Administrator',
  sopAdministrator: 'SOP Administrator',
  confirmCompared:
    'Main tasdeeq karta hun ke maine is content ka asal source se muqabla kiya hai.',
  indexVerified: 'Index verify ho gaya — publish ke liye tayyar',
  structureApproved: 'Structure manzoor ho gayi',
  correctionsSaved: 'Durustgiyan mehfooz ho gayin',
  saveCorrection: 'Durustgi mehfooz karein',
  submitReview: 'Review jama karein',
  prepareSearchIndex: 'Search index tayyar karein',
  publish: 'Publish karein',
  reviewUnavailable: 'Review dastiyab nahin',
  reviewUnavailableDetail:
    'Source aap ke daire se bahar, dastiyab nahin, ya API offline ho sakti hai.',
  extractionUnavailable: 'Extraction dastiyab nahin',
  extractionUnavailableDetail:
    'Canonical review se pehle is format ke liye parser provider darkar hai.',
  originalStructuredView: 'Asal structured view',
  orderedList: 'Number wali fehrist',
  unorderedList: 'Bullet fehrist',
};
export function useAdminCopy() {
  const { language } = useLanguage();
  return {
    copy:
      language === 'urdu'
        ? urdu
        : language === 'roman_urdu'
          ? roman_urdu
          : english,
    language,
  };
}
export function localizedStatus(label: string, copy: Copy): string {
  const key: Record<string, keyof Copy> = {
    Published: 'statusPublished',
    Draft: 'statusDraft',
    Processing: 'statusProcessing',
    'Review Required': 'statusReviewRequired',
    'Ready for Review': 'statusReady',
    Failed: 'statusFailed',
    Superseded: 'statusSuperseded',
  };
  return copy[key[label] ?? 'statusDraft'];
}
export function localizedSort(label: string, copy: Copy): string {
  const key: Record<string, keyof Copy> = {
    'Recently Updated': 'sortRecent',
    'Title A–Z': 'sortTitle',
    'Newest Version': 'sortVersion',
    Status: 'sortStatus',
  };
  return copy[key[label] ?? 'sortRecent'];
}
export function localizedSource(format: string, copy: Copy): string {
  if (format === 'scanned_pdf') return copy.scannedPdf;
  if (format === 'image') return copy.image;
  if (format === 'structured_text') return copy.structuredText;
  return sourceLabel(format);
}
